
import { Language, Difficulty, Topic } from './types';

export const QUESTIONS_PER_BLOCK = 4;
export const QUESTION_TIME_LIMIT = 20; // seconds

export const DIFFICULTY_LEVELS: Difficulty[] = ['easy', 'medium', 'hard'];

export const TOPICS: Topic[] = [
  {
    id: 'Antico Testamento',
    icon: 'M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z',
  },
  {
    id: 'Nuovo Testamento',
    icon: 'M12 6.042A8.967 8.967 0 006 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 016 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 016-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0018 18a8.967 8.967 0 00-6 2.292m0-14.25v14.25',
  },
  {
    id: 'Vangeli',
    icon: 'M19.5 14.25v-2.625a3.375 3.375 0 00-3.375-3.375h-1.5A1.125 1.125 0 0113.5 7.125v-1.5a3.375 3.375 0 00-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 00-9-9z',
  },
  {
    id: 'Profeti',
    icon: 'M10.5 1.5H8.25A2.25 2.25 0 006 3.75v16.5a2.25 2.25 0 002.25 2.25h7.5A2.25 2.25 0 0018 20.25V3.75a2.25 2.25 0 00-2.25-2.25H13.5m-3 0V3h3V1.5m-3 0h3m-3 18.75h3',
  },
];

export const STRINGS: Record<Language, any> = {
  it: {
    welcomeTitle: 'Quiz Biblico',
    welcomeSubtitle: 'Metti alla prova la tua conoscenza della Sacra Bibbia.',
    selectLanguage: 'Seleziona Lingua',
    selectTopic: 'Seleziona un Argomento',
    selectDifficulty: 'Seleziona la Difficoltà',
    loading: 'Caricamento domande...',
    viewHistory: 'Vedi Cronologia',
    confirmClearHistory: 'Sei sicuro di voler cancellare tutta la cronologia?',
    difficultyIncreased: 'Ottimo lavoro! La difficoltà è aumentata.',
    difficultyDecreased: 'La difficoltà è diminuita. Non mollare!',
    backToTopics: 'Torna agli Argomenti',
    topic: 'Argomento',
    score: 'Punteggio',
    question: 'Domanda',
    timeLeft: 'Tempo rimasto',
    nextQuestion: 'Prossima Domanda',
    viewResults: 'Vedi Risultati',
    resultsFor: 'Risultati per',
    correctAnswers: 'risposte corrette',
    successPercentage: 'Percentuale di successo',
    blockScore: 'Punteggio Blocco',
    totalScore: 'Punteggio Totale',
    playAgain: 'Gioca Ancora',
    history: 'Cronologia Partite',
    date: 'Data',
    difficulty: 'Difficoltà',
    clearHistory: 'Cancella Cronologia',
    noHistory: 'Nessuna partita trovata nella cronologia.',
  },
  en: {
    welcomeTitle: 'Bible Quiz',
    welcomeSubtitle: 'Test your knowledge of the Holy Bible.',
    selectLanguage: 'Select Language',
    selectTopic: 'Select a Topic',
    selectDifficulty: 'Select Difficulty',
    loading: 'Loading questions...',
    viewHistory: 'View History',
    confirmClearHistory: 'Are you sure you want to clear all history?',
    difficultyIncreased: 'Great job! Difficulty has increased.',
    difficultyDecreased: 'Difficulty has decreased. Keep trying!',
    backToTopics: 'Back to Topics',
    topic: 'Topic',
    score: 'Score',
    question: 'Question',
    timeLeft: 'Time left',
    nextQuestion: 'Next Question',
    viewResults: 'View Results',
    resultsFor: 'Results for',
    correctAnswers: 'correct answers',
    successPercentage: 'Success rate',
    blockScore: 'Block Score',
    totalScore: 'Total Score',
    playAgain: 'Play Again',
    history: 'Game History',
    date: 'Date',
    difficulty: 'Difficulty',
    clearHistory: 'Clear History',
    noHistory: 'No games found in history.',
  },
  pt: {
    welcomeTitle: 'Quiz da Bíblia',
    welcomeSubtitle: 'Teste seus conhecimentos sobre a Bíblia Sagrada.',
    selectLanguage: 'Selecione o idioma',
    selectTopic: 'Selecione um Tópico',
    selectDifficulty: 'Selecione a Dificuldade',
    loading: 'Carregando perguntas...',
    viewHistory: 'Ver Histórico',
    confirmClearHistory: 'Tem certeza de que deseja limpar todo o histórico?',
    difficultyIncreased: 'Ótimo trabalho! A dificuldade aumentou.',
    difficultyDecreased: 'A dificuldade diminuiu. Continue tentando!',
    backToTopics: 'Voltar aos Tópicos',
    topic: 'Tópico',
    score: 'Pontuação',
    question: 'Pergunta',
    timeLeft: 'Tempo restante',
    nextQuestion: 'Próxima Pergunta',
    viewResults: 'Ver Resultados',
    resultsFor: 'Resultados para',
    correctAnswers: 'respostas corretas',
    successPercentage: 'Taxa de sucesso',
    blockScore: 'Pontuação do Bloco',
    totalScore: 'Pontuação Total',
    playAgain: 'Jogar Novamente',
    history: 'Histórico de Jogos',
    date: 'Data',
    difficulty: 'Dificuldade',
    clearHistory: 'Limpar Histórico',
    noHistory: 'Nenhum jogo encontrado no histórico.',
  },
  es: {
    welcomeTitle: 'Quiz Bíblico',
    welcomeSubtitle: 'Pon a prueba tus conocimientos de la Santa Biblia.',
    selectLanguage: 'Seleccione el idioma',
    selectTopic: 'Selecciona un Tema',
    selectDifficulty: 'Selecciona la Dificultad',
    loading: 'Cargando preguntas...',
    viewHistory: 'Ver Historial',
    confirmClearHistory: '¿Estás seguro de que quieres borrar todo el historial?',
    difficultyIncreased: '¡Gran trabajo! La dificultad ha aumentado.',
    difficultyDecreased: 'La dificultad ha disminuido. ¡Sigue intentándolo!',
    backToTopics: 'Volver a los Temas',
    topic: 'Tema',
    score: 'Puntuación',
    question: 'Pregunta',
    timeLeft: 'Tiempo restante',
    nextQuestion: 'Siguiente Pregunta',
    viewResults: 'Ver Resultados',
    resultsFor: 'Resultados de',
    correctAnswers: 'respuestas correctas',
    successPercentage: 'Tasa de éxito',
    blockScore: 'Puntuación del Bloque',
    totalScore: 'Puntuación Total',
    playAgain: 'Jugar de Nuevo',
    history: 'Historial de Juegos',
    date: 'Fecha',
    difficulty: 'Dificultad',
    clearHistory: 'Borrar Historial',
    noHistory: 'No se encontraron juegos en el historial.',
  },
  fr: {
    welcomeTitle: 'Quiz Biblique',
    welcomeSubtitle: 'Testez vos connaissances de la Sainte Bible.',
    selectLanguage: 'Sélectionnez la langue',
    selectTopic: 'Sélectionnez un Sujet',
    selectDifficulty: 'Sélectionnez la Difficulté',
    loading: 'Chargement des questions...',
    viewHistory: 'Voir l\'Historique',
    confirmClearHistory: 'Êtes-vous sûr de vouloir effacer tout l\'historique ?',
    difficultyIncreased: 'Excellent travail ! La difficulté a augmenté.',
    difficultyDecreased: 'La difficulté a diminué. Continuez d\'essayer !',
    backToTopics: 'Retour aux Sujets',
    topic: 'Sujet',
    score: 'Score',
    question: 'Question',
    timeLeft: 'Temps restant',
    nextQuestion: 'Question Suivante',
    viewResults: 'Voir les Résultats',
    resultsFor: 'Résultats pour',
    correctAnswers: 'réponses correctes',
    successPercentage: 'Taux de réussite',
    blockScore: 'Score du Bloc',
    totalScore: 'Score Total',
    playAgain: 'Rejouer',
    history: 'Historique des Jeux',
    date: 'Date',
    difficulty: 'Difficulté',
    clearHistory: 'Effacer l\'Historique',
    noHistory: 'Aucun jeu trouvé dans l\'historique.',
  },
  de: {
    welcomeTitle: 'Bibel-Quiz',
    welcomeSubtitle: 'Testen Sie Ihr Wissen über die Heilige Schrift.',
    selectLanguage: 'Sprache auswählen',
    selectTopic: 'Wählen Sie ein Thema',
    selectDifficulty: 'Wählen Sie den Schwierigkeitsgrad',
    loading: 'Fragen werden geladen...',
    viewHistory: 'Verlauf anzeigen',
    confirmClearHistory: 'Sind Sie sicher, dass Sie den gesamten Verlauf löschen möchten?',
    difficultyIncreased: 'Gute Arbeit! Der Schwierigkeitsgrad wurde erhöht.',
    difficultyDecreased: 'Der Schwierigkeitsgrad wurde verringert. Versuchen Sie es weiter!',
    backToTopics: 'Zurück zu den Themen',
    topic: 'Thema',
    score: 'Punktzahl',
    question: 'Frage',
    timeLeft: 'Verbleibende Zeit',
    nextQuestion: 'Nächste Frage',
    viewResults: 'Ergebnisse anzeigen',
    resultsFor: 'Ergebnisse für',
    correctAnswers: 'richtige Antworten',
    successPercentage: 'Erfolgsquote',
    blockScore: 'Block-Punktzahl',
    totalScore: 'Gesamtpunktzahl',
    playAgain: 'Erneut spielen',
    history: 'Spielverlauf',
    date: 'Datum',
    difficulty: 'Schwierigkeitsgrad',
    clearHistory: 'Verlauf löschen',
    noHistory: 'Keine Spiele im Verlauf gefunden.',
  },
};

export const getDifficultyName = (difficulty: Difficulty, language: Language): string => {
    const names: Record<Language, Record<Difficulty, string>> = {
      it: { easy: 'Facile', medium: 'Medio', hard: 'Difficile' },
      en: { easy: 'Easy', medium: 'Medium', hard: 'Hard' },
      pt: { easy: 'Fácil', medium: 'Médio', hard: 'Difícil' },
      es: { easy: 'Fácil', medium: 'Medio', hard: 'Difícil' },
      fr: { easy: 'Facile', medium: 'Moyen', hard: 'Difficile' },
      de: { easy: 'Leicht', medium: 'Mittel', hard: 'Schwer' },
    };
    return names[language][difficulty];
  };
